DATA SEGMENT 
    STRING1 DB 01H,02H,03H,04H,05H
ENDS
EXTRA SEGMENT
    STRING2 DB ?
ENDS
CODE SEGMENT 
    START:
    MOV AX,DATA 
    MOV DS,AX
    MOV AX,EXTRA
    MOV ES,AX
    LEA SI,STRING1
    LEA DI ,STRING2
    MOV CL,05H
    ABC:
    MOV AL,DS:[SI]
    MOV ES:[DI],AL
    INC SI
    INC DI 
    DEC CL
    JNZ ABC
    HLT
    CODE ENDS
END START
        